### ISSUE TITLE
argparse nargs=1 actually generates a single-element list

### ISSUE THREAD

**Issue by lukegb** [jelmer/redirect-webfinger#1]
From my local testing, I couldn't get the webfinger endpoint to match properly.

I think `parser.add_argument(..., nargs=1, ...)` actually causes `args.acct` (etc.) to be single-element lists, so then `app['acct']` becomes e.g. `['lukegb@lukegb.com']` rather than `'lukegb@lukegb.com'` so then the `supported_resource` check never matches.

**Comment by jelmer** [comment]
Whoops, you're right - fixed in main. I originally had these hardcoded, so didn't notice..
